# Taps
tap 'homebrew/bundle'

# Binaries
brew 'adr-tools'
brew 'awscli'
brew 'coreutils' # Those that come with macOS are outdated
brew 'eza'
brew 'fd'
brew 'ffmpeg'
brew 'gh'
brew 'git'
brew 'gnupg'
brew 'grep'
brew 'htop'
brew 'httpie'
brew 'libffi'
brew 'libpng'
brew 'mackup'
brew 'mas' # Mac App Store manager
brew 'ncurses'
brew 'neovim'
brew 'openblas'
brew 'openjdk'
brew 'openssl'
brew 'pyenv'
brew 'pinentry-mac'
brew 'pipx'
brew 'readline'
brew 'sqlite3'
brew 'starship'
brew 'svn' # Needed to install fonts
brew 'wget'
brew 'xz'
brew 'zlib'
brew 'zstd'

# Fonts
cask 'font-fira-code'
cask 'font-hack-nerd-font'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
