format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
| \
$package\
$python\
$line_break\
$cmd_duration\
$character"""

[directory]
style = "blue"

[hostname]
ssh_only = true
format = "@[$hostname](bold red) "
disabled = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[package]
format = "[$symbol$version]($style) "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'
style = "green"
